server:
  port: 8086
  servlet:
    context-path: /im-user-client
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender:
      type: web
  sleuth:
    #web:
      #enabled: true
    #trace-id128: true
    sampler:
      probability: 1.0
  application:
    name: im-user-client
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    lettuce: 
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: -1
        max-active: 8
  #cloud:
    #gateway:
      #default-filters:
      #discovery:
        #locator:
          #enabled: false
          #lowerCaseServiceId: true
#feign:
  #hystrix:
    #enabled: true
  #client:
    #config:
      #服务名，填写default为所有服务
      #remoteService:           
        #connectTimeout: 1000
        #readTimeout: 12000
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:wanghao@127.0.0.1:8888/ek-server/eureka/
jwt: 
  expiration: 
    time: 120000
#logging:
  #file:
    #name: im-user-client
    #path: D:\im-logs\logs